eureka:
  client:
    registerWithEureka: true #注册服务
    fetchRegistry: true #从服务端获取服务注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: my-service
server:
  port: 8080
